### PR TITLE
Composer performance

### PR DESCRIPTION
**Pull request by melnikovi**

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/architecture?pullRequest=218) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/architecture?pullRequest=218) before we can accept your contribution.<br/>

**Comment by fascinosum** [comment]
Irrelevant due to Composer 2 release and support of Composer 2 installation start from 2.4.2

**Comment by hostep** [comment]
Not all suggestions in this PR are solved with moving to composer 2.

Not creating `dev` directory when you run composer with `--no-dev`, is being tracked by https://github.com/magento/magento2/issues/5262 & https://github.com/magento/magento2/issues/8971

There was also a ticket (incorrectly?) closed recently where it was asked to move all development dependencies to a separate package, it was closed because it was claimed that `magento/composer-root-update-plugin` solved that, but that's strictly speaking not true: https://github.com/magento/architecture/pull/351

**Comment by fascinosum** [comment]
Hi @hostep,
thank you for your attention to this.

Let's walk through this one by one:

1. **Use plugin that allows parallel download of the packages** - Usage of the plugin is [not recommended](https://github.com/hirak/prestissimo#announcement-composer-2-is-now-available) with Composer 2
2. **Use a metapackage for `require-dev` section** - This was discussed in #351, see [comment](https://github.com/magento/architecture/pull/351#issuecomment-730828241) from @paliarush 
3. **Not creating `dev/` directory when you run composer with `--no-dev`** - As you can see the result of discussion in https://github.com/magento/magento2/issues/8971, this feature has low priority. MAGETWO-52095 internal ticket for https://github.com/magento/magento2/issues/5262 has not been closed. We will review again it's priority

**Pull request closed without merging**
