### PR TITLE
Document regarding controllers extending each other

### PR DESCRIPTION
**Pull request by AlexMaxHorkun**
## Problem

Extending backend controllers in frontend controllers may lead to unexpected behavior

## Solution

Create a PHPStan rule to prevent this

## Requested Reviewers

@buskamuza

### CODE REVIEW

**Comment by lenaorobei** [comment]
I like the idea of this rule, but my only one concern in the use of `PHPMD `. Right now I'm working on replacing some Magento PHPMD rules with PHPCS, but it's impossible for some cases (like this one) where we need to use Reflection. 

I'm working on proposal to get rid of PHPMD and use PHPStan instead. It's widely used now, actively developed and supported. Latest release of [PHPMD on Jan 20, 2017](https://github.com/phpmd/phpmd/releases), [PHPStan - Feb 12, 2019](https://github.com/phpstan/phpstan/releases).  Few more numbers with default rulesets:

|  | PHPStan | PHPMD |
| ------------- | ------------- |------------- |
| Time to analyse single module (Magento/AdminNotification)  | 0m1.711s  | 0m36.907s |
| Time to analyse Magento app/code  | 8m12.334s | 132m58.415s |

**Comment by AlexMaxHorkun** [comment]
> I like the idea of this rule, but my only one concern in the use of PHPMD. Right now I'm working on replacing some Magento PHPMD rules with PHPCS, but it's impossible for some cases (like this one) where we need to use Reflection.
> 
> I'm working on proposal to get rid of PHPMD and use PHPStan instead. It's widely used now, actively developed and supported. Latest release of [PHPMD on Jan 20, 2017](https://github.com/phpmd/phpmd/releases), [PHPStan - Feb 12, 2019](https://github.com/phpstan/phpstan/releases). Few more numbers with default rulesets:
> 
> PHPStan	PHPMD
> Time to analyse single module (Magento/AdminNotification)	0m1.711s	0m36.907s
> Time to analyse Magento app/code	8m12.334s	132m58.415s

If we're going to recreate all other rules we might as well recreate this one when moving to PHPStan

**Comment by melnikovi** [comment]
@AlexMaxHorkun we [decided to introduce PHPStan](https://github.com/magento/architecture/pull/114), could change PHPMD to PHPStan in the proposal?

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/architecture?pullRequest=101) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/architecture?pullRequest=101) before we can accept your contribution.<br/>

**Comment by AlexMaxHorkun** [comment]
> @AlexMaxHorkun we [decided to introduce PHPStan](https://github.com/magento/architecture/pull/114), could change PHPMD to PHPStan in the proposal?

Updated

**Pull request merged**
