### PR TITLE
Initial architecture proposal for using a meta package for require-dev

### PR DESCRIPTION
**Pull request by dverkade**
## Problem

No longer need to update the require-dev packages in the root composer.json

## Solution

Create a meta package referencing the needed packages to be loaded in the require-dev section. 

## Requested Reviewers

- @joni-jones
- @buskamuza
- @paliarush

### CODE REVIEW

**Comment by milindsingh** [comment]
Yes, this would be very nice. and also, I would suggest that dev dependencies are not added by default.

**Comment by fascinosum** [comment]
hi @pdohogne-magento,
could you confirm that `magento/composer-root-update-plugin` fulfills this requirement?

**Comment by pdohogne-magento** [comment]
@fascinosum The plugin makes updating the root composer.json file automatic so the manual steps of updating the `require-dev` section are no longer necessary.  Moving the requirements to a metapackage is still potentially a good idea, though, as it provides a clean way for users to remove all dev dependencies if desired and potentially makes it easier for us to make dev dependencies optional in the future if we decide to go that route.

**Comment by dverkade** [comment]
@paliarush why is this being closed?

**Comment by paliarush** [comment]
@dverkade mainly because updates to root composer are now automated by the `magento/composer-root-update-plugin` plugin (as confirmed by @pdohogne-magento above), which satisfies the use case described in "The Problem" section of the proposal.

Moving dev dependencies to a separate metapackage would be nice to have. Unfortunately, such change would require modifications of Magento release publication process and related automation. In addition, this may cause backward incompatibility for the CI infrastructure of system integrators and merchants. So there must be a very good reason to justify such risks.

**Pull request closed without merging**
