### PR TITLE
New way to code generate Interceptors

### PR DESCRIPTION
**Pull request by maghamed**
## Problem

Existing debugging of Magento may be tricky because of Interception implementation via dynamical calls of `___callPlugins`  in the call stack.

## Solution

The idea is to use a mechanism which generates Interceptors code using app config instead of reading config at runtime.

#### Current Code generated Interceptors

```php
public function methodX($arg) {
    $pluginInfo = $this->pluginList->getNext($this->subjectType, 'methodX');
    if (!$pluginInfo) {
        return parent::methodX($arg);
    } else {
        return $this->___callPlugins('methodX', func_get_args(), $pluginInfo);
    }
}
```

#### Proposed version of Code generated Interceptors 

```php
public function methodX($arg) {
    switch(getCurrentScope()){
        case 'frontend':
            $this->_get_example_plugin()->beforeMethodX($this, $arg);
            $this->_get_another_plugin()->beforeMethodX($this, $arg);
            $result = $this->_get_around_plugin()->aroundMethodX($this, function($arg){
                return parent::methodX($arg);
            });
            return $this->_get_after_plugin()->afterMethodX($this, $result);
        case 'adminhtml':
            // ...
        default:
            return parent::methodX($arg);
    }
}
```

## Links

1. PR with code changes created by @fsw https://github.com/magento/magento2/pull/22826
2. [YouTube recording of Architectural Discussion](https://www.youtube.com/watch?v=no2jVn_mixk&list=PLDvMskiz68Q3ZVyRsc59IjEqX85LaO8mr&index=16)
3. https://github.com/creatuity/magento2-interceptors

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/architecture?pullRequest=185) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/architecture?pullRequest=185) before we can accept your contribution.<br/>

**Comment by gamort** [comment]
How would this handle CLI/Cron plugins?

**Comment by fsw** [comment]
@gamort 
> How would this handle CLI/Cron plugins?

Generated code has a case for all possible areas including "crontab" area:

```
public function methodX($arg) {
    switch(getCurrentScope()){
        case 'frontend':
            // ...
        case 'adminhtml':
            // ...
        case 'crontab':
            // ...
        case 'global':
            // ...
           // ETC
        default:
            return parent::methodX($arg);
    }
}
```
CLI commands can set their area in runtime in some cases so this should call exactly the plugins that are called with current approach.

**Comment by buskamuza** [comment]
Poll https://twitter.com/iminyaylo/status/1136757248099852288

**Comment by joshuaadickerson** [comment]
Sorry @maghamed I had a review pending for a long time. Didn't mean to submit it.

**Comment by maghamed** [comment]
@joshuaadickerson  the PR got all the sign off from the Architectural side and waiting to be processed and merged by Community Engineering team

**Pull request merged**
