### PR TITLE
Add proposal to deprecate JS Component mixins

### PR DESCRIPTION
**Pull request by DrewML**
Originally from https://github.com/magento/magento2/issues/17842

### CODE REVIEW

**Comment by Igloczek** [comment]
This is the first time I see the second meaning of `mixins`, so from my perspective would be better to deprecate, rather than documenting it.

**Comment by DrewML** [comment]
Will be discussed at the September 5th arch meeting: https://github.com/magento/architecture/wiki/September-5,-2018

**Comment by Vinai** [comment]
Moar unscientific research: https://twitter.com/VinaiKopp/status/1039540483691827200

**Comment by DrewML** [comment]
Update: Still pending running some static analysis to verify lack of usage. Will be following up on that in the next week

**Comment by DrewML** [comment]
We're very likely going forward with this, but I'm just waiting on the scan over popular extensions to verify there aren't use-cases we didn't consider

**Comment by DrewML** [comment]
Confirmed none of the large extensions in the marketplace are using this functionality, and have not found anyone in the community relying on this functionality.

We'll move forward with the deprecation. The work will likely need to be done in concert with #33 as the Fotorama implementation is currently the only consumer of this undocumented API.

**Pull request merged**
